apiVersion: apps/v1
kind: Deployment
metadata:
  name: kube-blitz-controller
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kube-blitz-controller
  template:
    metadata:
      labels:
        app: kube-blitz-controller
    spec:
      containers:
      - name: kube-blitz-controller
        image: kube-blitz-controller:latest
        # Add additional container configuration as needed
