# permissions for end users to edit loadtests.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: loadtest-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: kube-blitz
    app.kubernetes.io/part-of: kube-blitz
    app.kubernetes.io/managed-by: kustomize
  name: loadtest-editor-role
rules:
- apiGroups:
  - load-test.kubeblitz.com
  resources:
  - loadtests
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - load-test.kubeblitz.com
  resources:
  - loadtests/status
  verbs:
  - get
